services:
  backend:
    build:
      context: ./email-classifier.backend
      dockerfile: Dockerfile
    env_file:
      - ./email-classifier.backend/.env
    ports:
      - "3001:3001"
    depends_on:
      - redis
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./email-classifier.frontend
      dockerfile: Dockerfile
    env_file:
      - ./email-classifier.frontend/.env
    ports:
      - "3000:3000"
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
