version: '3.8'

services:
  mongo:
    image: mongo:7.0
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: email-classifier
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
